# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felipeblini.net" # the base hostname & protocol for your site

title:  Felipe Blini - Angular Developer and Consultant
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
# for build the multilanguage menu
t:
  pt:
    country: br
    lang: pt
    pages:
        about:
            name: "Sobre"
            url: "/about/"
  en:
    country: us
    lang: en
    pages:
        about:
            name: "About"
            url: "/en/about/"
            
resources:
    pt:
        footer_text_below_icons: "Veja como esse icones foram feitos no"
        source_code: "código fonte:"
        and: "e"
        made_with: "feito com"
        minutes_to_read: "minuto(s) de leitura"
    en:
        footer_text_below_icons: "See how this icons was made in"
        source_code: "source code:"
        and: "and"
        made_with: "made with"
        minutes_to_read: "minute(s) to read"

theme:
    # Scripts
    disqus_shortname: felipeblini
    katex: false # Enable if using math markup
    fontawesome: true

    # Colours, typography and padding
    # Open the "_sass > base" folder, and open "_variables.scss"
    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
    
    email: "felipe@blini.io"
    whatsapp: "+55 18 9 8207 0863"
    skype: "blini_bra"

# PAGINATION
# paginate: 5
# paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
# gems: [jekyll-paginate]