# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blini.io" # the base hostname & protocol for your site

title:  "blini.io - JavaScript, AngularJS, Ionic, PWA, Node, Express, .NET e tudo sobre web"
description: > # this means to ignore newlines until "baseurl:"
  blini.io - JavaScript, AngularJS, Ionic, PWA, Node, Express, .NET e tudo sobre web

  
# for build the multilanguage menu
t:
  pt:
    country: br
    lang: pt
    pages:
        courses:
            name: "Cursos"
            url: "/cursos/"
        about:
            name: "Sobre"
            url: "/about/"
  en:
    country: us
    lang: en
    pages:
        courses:
            name: "Courses"
            url: "/cursos/"
        about:
            name: "About"
            url: "/en/about/"
            
resources:
    pt:
        footer_text_below_icons: "Veja como esse icones foram feitos no"
        source_code: "código fonte:"
        and: "e"
        made_with: "feito com"
        minutes_to_read: "minuto(s) de leitura"
        forms:
            newsletters:
                title: 'Assine a newsletters'
            placeholders:
                name: nome
                email: seu@email.com
                surname: sobrenome
            labels:
                submit: Enviar
    en:
        footer_text_below_icons: "See how these icons at"
        source_code: "source code:"
        and: "and"
        made_with: "made with"
        minutes_to_read: "minute(s) to read"
        forms:
            newsletters:
                title: 'Newsletters'
            placeholders:
                name: name
                email: your@email.com
                surname: surname
            labels:
                submit: Send

theme:
    # Scripts
    disqus_shortname: felipeblini
    katex: false # Enable if using math markup
    fontawesome: true

    # Colours, typography and padding
    # Open the "_sass > base" folder, and open "_variables.scss"
    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
    
    email: "felipe@blini.io"
    whatsapp: "+55 11 9 7036 2125"
    skype: "blini_bra"
    phone: "+55 18 9 8115 6331"

# PAGINATION
# paginate: 5
# paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed
# gems: [jekyll-paginate]